<?php

namespace JeanDeJean\Bundle\PortfolioBundle\Entity\Portfolio;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
  public function getHomePage()
  {
    $homepage = $this->findOneBy(array("home" => 1));
    if (null === $homepage) {
      $homepage = $this->findOneBy(array(), array('id' => 'DESC'));
    }
    
    return $homepage;
  }
}
